config {
  type: "view",
  schema: "dados_alagoinhas_gold",
  name: "acidentedetrabalho_alagoinhas_gold_v",
  description: "Dados consolidados de acidentes de trabalho para o município de Alagoinhas/BA",

labels: {
  autor: "luciano",
  departamento: "saude"
},

columns: {
  tipo_notificacao:"Define o tipo de notificação referente ao acidente de trabalho",
  id_agravo:"Código do agravo",
  data_notificacao:"Data da notificação na unidade de saúde",
  semana_notificacao: "Semana da notificação na unidade de saúde",
  ano: "Ano da notificação na unidade de saúde",
  uf_notificacao:""
}}


SELECT 
  TP_NOT AS tipo_notificacao,
  ID_AGRAVO AS id_agravo,
  DT_NOTIFIC AS data_notificacao,
  SEM_NOT AS semana_notificacao,
  NU_ANO AS ano,
  SG_UF_NOT AS uf_notificacao,
  ID_MUNICIP AS id_municipio,
  ID_REGIONA AS id_regiao,
  ID_UNIDADE AS unidade_notificadora,
  DT_ACID AS data_acidente,
  SEM_ACID AS semana_acidente,
  ANO_NASC AS ano_nasc,

  --tratamento idade
  CASE 
    WHEN NU_IDADE_N >= 4000 AND NU_IDADE_N < 5000 THEN NU_IDADE_N - 4000
    WHEN NU_IDADE_N < 4000 THEN 0
    ELSE NULL 
  END AS idade_em_anos,

  --tratamento sexo
  CASE
    WHEN CS_SEXO = 'F' THEN 'Feminino'
    WHEN CS_SEXO = 'M' THEN 'Masculino'
    WHEN CS_SEXO = 'I' THEN 'Ignorado'
  END AS sexo,

-- tratamento raça cor
  CASE 
    WHEN CS_RACA = 1 THEN 'Branca'
    WHEN CS_RACA = 2 THEN 'Preta'
    WHEN CS_RACA = 3 THEN 'Amarela'
    WHEN CS_RACA = 4 THEN 'Parda'
    WHEN CS_RACA = 9 THEN 'Ignorado'
    ELSE 'Não preenchido'
  END AS raca,

-- tratamento tipo de acidente
  CASE 
    WHEN TIPO_ACID = 1 THEN 'Típico'
    WHEN TIPO_ACID = 2 THEN 'Trajeto'
    WHEN TIPO_ACID = 9 THEN 'Ignorado'
    WHEN TIPO_ACID IS NULL THEN 'Não preenchido'
    ELSE 'Valor Inválido/Outros'
  END AS desc_tipo_acidente,

-- tratamento parte do corpo

------primeira parte do corpo ------
CASE PART_CORP1
        WHEN 1 THEN 'Olho'
        WHEN 2 THEN 'Cabeça'
        WHEN 3 THEN 'Pescoço'
        WHEN 4 THEN 'Tórax'
        WHEN 5 THEN 'Abdome/Pelve'
        WHEN 6 THEN 'Mão'
        WHEN 7 THEN 'Membro Superior'
        WHEN 8 THEN 'Membro Inferior'
        WHEN 9 THEN 'Pé'
        WHEN 10 THEN 'Todo o corpo'
        WHEN 11 THEN 'Outro'
        WHEN 99 THEN 'Ignorado'
        ELSE 'Não preenchido' 
    END AS parte_corpo_1,

------segunda parte do corpo ------
CASE PART_CORP2
        WHEN 1 THEN 'Olho'
        WHEN 2 THEN 'Cabeça'
        WHEN 3 THEN 'Pescoço'
        WHEN 4 THEN 'Tórax'
        WHEN 5 THEN 'Abdome/Pelve'
        WHEN 6 THEN 'Mão'
        WHEN 7 THEN 'Membro Superior'
        WHEN 8 THEN 'Membro Inferior'
        WHEN 9 THEN 'Pé'
        WHEN 10 THEN 'Todo o corpo'
        WHEN 11 THEN 'Outro'
        WHEN 99 THEN 'Ignorado'
        ELSE 'Não preenchido' 
    END AS parte_corpo_2,

------terceira parte do corpo ------
CASE PART_CORP3
        WHEN 1 THEN 'Olho'
        WHEN 2 THEN 'Cabeça'
        WHEN 3 THEN 'Pescoço'
        WHEN 4 THEN 'Tórax'
        WHEN 5 THEN 'Abdome/Pelve'
        WHEN 6 THEN 'Mão'
        WHEN 7 THEN 'Membro Superior'
        WHEN 8 THEN 'Membro Inferior'
        WHEN 9 THEN 'Pé'
        WHEN 10 THEN 'Todo o corpo'
        WHEN 11 THEN 'Outro'
        WHEN 99 THEN 'Ignorado'
        ELSE 'Não preenchido' 
    END AS parte_corpo_3,

----tratamento gestante

CASE CS_GESTANT
    WHEN 1 THEN '1º Trimestre'
    WHEN 2 THEN '2º Trimestre'
    WHEN 3 THEN '3º Trimestre'
    WHEN 4 THEN 'Idade gestacional ignorada'
    WHEN 5 THEN 'Não'
    WHEN 6 THEN 'Não se aplica'
    WHEN 9 THEN 'Ignorado'
    ELSE 'Não Informado' 
  END AS situacao_gestacional,


-- tratamento escolaridade

CASE CAST(CS_ESCOL_N AS STRING) 
    WHEN '0' THEN 'Analfabeto'
    WHEN '1' THEN '1ª a 4ª série incompleta do EF'
    WHEN '2' THEN '4ª série completa do EF'
    WHEN '3' THEN '5ª à 8ª série incompleta do EF'
    WHEN '4' THEN 'Ensino fundamental completo'
    WHEN '5' THEN 'Ensino médio incompleto'
    WHEN '6' THEN 'Ensino médio completo'
    WHEN '7' THEN 'Educação superior incompleta'
    WHEN '8' THEN 'Educação superior completa'
    WHEN '9' THEN 'Ignorado'
    WHEN '10' THEN 'Não se aplica'
    ELSE 'Não informado' 
  END AS escolaridade,

-- tratamento situação de trabalho

CASE CAST(SIT_TRAB AS STRING)
    WHEN '1' THEN 'Empregado registrado CLT'
    WHEN '2' THEN 'Empregado não registrado'
    WHEN '3' THEN 'Autônomo'
    WHEN '4' THEN 'Servidor público estatutário'
    WHEN '5' THEN 'Servidor público celetista'
    WHEN '6' THEN 'Aposentado'
    WHEN '7' THEN 'Desempregado'
    WHEN '8' THEN 'Trabalho temporário'
    WHEN '9' THEN 'Cooperativado'
    WHEN '10' THEN 'Trabalhador avulso'
    WHEN '11' THEN 'Empregador'
    WHEN '12' THEN 'Outros'
    WHEN '99' THEN 'Ignorado'
    ELSE 'Não informado'
  END AS situacao_trabalho,

-- tratamento atendimento médico

  CASE CAST(ATENDE_MED AS STRING)
    WHEN '1' THEN 'Sim'
    WHEN '2' THEN 'Não'
    WHEN '9' THEN 'Ignorado'
    ELSE 'Não informado'
  END AS recebeu_atendimento_medico,


-- referencial da tabela
FROM
  ${ref("acidentes_de_trabalho_silver")}