config {
  type: "view",
  schema: "dados_alagoinhas_gold",
  name: "acidentedetrabalho_alagoinhas_gold_v",
  description: "Dados consolidados de acidentes de trabalho para o município de Alagoinhas/BA",

labels: {
  autor: "luciano",
  departamento: "saude"
},

columns: {
  tipo_notificacao:"Define o tipo de notificação referente ao acidente de trabalho",
  id_agravo:"Código do agravo",
  data_notificacao:"Data da notificação na unidade de saúde",
  semana_notificacao: "Semana da notificação na unidade de saúde",
  ano: "Ano da notificação na unidade de saúde",
  uf_notificacao:"Unidade federativa da ocorrência",
  id_municipio:"Código do IBGE para o múnicipio da ocorrência",
  id_regiao: "Código da macro região",
  unidade_notificadora: "Unidade de saúde que recebeu a notificação do acidente de trabalho",
  data_acidente: "Data da ocorrência do acidente (esta data é da ocorrência, não da notificação na US)",
  semana_acidente: "Semana em que correu a notificação (padrão em boletins epidemiologicos)",
  ano_nasc: "Ano de nascimento do paciente",
  idade_em_anos: "Idade do paciente",
  sexo: "Sexo do paciente",
  raca: "Raça/cor/grupo étnico do paciente",
  desc_tipo_acidente: "Tipo de acidente, sendo típico no ambiente de trabalho e trajeto no percuso até o trabalho",
  parte_corpo_1:"Descreve a primeira parte do corpo afetada (se houver só esta)",
  parte_corpo_2:"Descreve a segunda parte do corpo afetata (se houverem duas partes afetadas)",
  parte_corpo_3:"Descreve a terceira parte do corpo afetada (se houverem 3)",
  situacao_gestacional: "Descreve a situação gestacional das mulheres com agravos",
  escolaridade: "Descreve a escolaridade do paciente (útil para análises sociais)",
  situacao_trabalho: "Descreve o vínculo empregatício do trabalhador com o agravo",
  recebeu_atendimento_medico:"Descreve se o paciente recebeu atendimento médico/primeiros socorros",
  evolucao_caso: "Descreve a evolução do caso e os dados foram permanentes ou não, ou resultaram em óbito",
  regime_tratamento:"Descreve o tipo de regime de tratamento que o paciente recebeu"
}}


SELECT 
  TP_NOT AS tipo_notificacao,
  ID_AGRAVO AS id_agravo,
  DT_NOTIFIC AS data_notificacao,
  SEM_NOT AS semana_notificacao,
  NU_ANO AS ano,
  SG_UF_NOT AS uf_notificacao,
  ID_MUNICIP AS id_municipio,
  ID_REGIONA AS id_regiao,
  ID_UNIDADE AS unidade_notificadora,
  PARSE_DATE('%Y%m%d', CAST(DT_ACID AS STRING)) AS data_acidente,
  SEM_ACID AS semana_acidente,
  ANO_NASC AS ano_nasc,
  HORA_ACID AS hora_acidente,


-- coluna para turno

  CASE 
    WHEN HORA_ACID >= 0 AND HORA_ACID < 4 THEN 'Madrugada'
    WHEN HORA_ACID >= 4 AND HORA_ACID < 11 THEN 'Manhã'
    WHEN HORA_ACID >= 12 AND HORA_ACID < 18 THEN 'Vespertino'
    WHEN HORA_ACID >= 18 AND HORA_ACID <= 23 THEN 'Noturno'
    ELSE 'Inválido/ Não informado' 
  END AS turno_acidente,

  --tratamento idade
  CASE 
    WHEN NU_IDADE_N >= 4000 AND NU_IDADE_N < 5000 THEN NU_IDADE_N - 4000
    WHEN NU_IDADE_N < 4000 THEN 0
    ELSE NULL 
  END AS idade_em_anos,

  --tratamento sexo
  CASE
    WHEN CS_SEXO = 'F' THEN 'Feminino'
    WHEN CS_SEXO = 'M' THEN 'Masculino'
    WHEN CS_SEXO = 'I' THEN 'Ignorado'
  END AS sexo,

-- tratamento raça cor
  CASE 
    WHEN CS_RACA = 1 THEN 'Branca'
    WHEN CS_RACA = 2 THEN 'Preta'
    WHEN CS_RACA = 3 THEN 'Amarela'
    WHEN CS_RACA = 4 THEN 'Parda'
    WHEN CS_RACA = 9 THEN 'Ignorado'
    ELSE 'Não preenchido'
  END AS raca,

-- tratamento tipo de acidente
  CASE 
    WHEN TIPO_ACID = 1 THEN 'Típico'
    WHEN TIPO_ACID = 2 THEN 'Trajeto'
    WHEN TIPO_ACID = 9 THEN 'Ignorado'
    WHEN TIPO_ACID IS NULL THEN 'Não preenchido'
    ELSE 'Valor Inválido/Outros'
  END AS desc_tipo_acidente,

-- tratamento parte do corpo

------primeira parte do corpo ------
CASE PART_CORP1
        WHEN 1 THEN 'Olho'
        WHEN 2 THEN 'Cabeça'
        WHEN 3 THEN 'Pescoço'
        WHEN 4 THEN 'Tórax'
        WHEN 5 THEN 'Abdome/Pelve'
        WHEN 6 THEN 'Mão'
        WHEN 7 THEN 'Membro Superior'
        WHEN 8 THEN 'Membro Inferior'
        WHEN 9 THEN 'Pé'
        WHEN 10 THEN 'Todo o corpo'
        WHEN 11 THEN 'Outro'
        WHEN 99 THEN 'Ignorado'
        ELSE 'Não preenchido' 
    END AS parte_corpo_1,

------segunda parte do corpo ------
CASE PART_CORP2
        WHEN 1 THEN 'Olho'
        WHEN 2 THEN 'Cabeça'
        WHEN 3 THEN 'Pescoço'
        WHEN 4 THEN 'Tórax'
        WHEN 5 THEN 'Abdome/Pelve'
        WHEN 6 THEN 'Mão'
        WHEN 7 THEN 'Membro Superior'
        WHEN 8 THEN 'Membro Inferior'
        WHEN 9 THEN 'Pé'
        WHEN 10 THEN 'Todo o corpo'
        WHEN 11 THEN 'Outro'
        WHEN 99 THEN 'Ignorado'
        ELSE 'Não preenchido' 
    END AS parte_corpo_2,

------terceira parte do corpo ------
CASE PART_CORP3
        WHEN 1 THEN 'Olho'
        WHEN 2 THEN 'Cabeça'
        WHEN 3 THEN 'Pescoço'
        WHEN 4 THEN 'Tórax'
        WHEN 5 THEN 'Abdome/Pelve'
        WHEN 6 THEN 'Mão'
        WHEN 7 THEN 'Membro Superior'
        WHEN 8 THEN 'Membro Inferior'
        WHEN 9 THEN 'Pé'
        WHEN 10 THEN 'Todo o corpo'
        WHEN 11 THEN 'Outro'
        WHEN 99 THEN 'Ignorado'
        ELSE 'Não preenchido' 
    END AS parte_corpo_3,

----tratamento gestante

CASE CS_GESTANT
    WHEN 1 THEN '1º Trimestre'
    WHEN 2 THEN '2º Trimestre'
    WHEN 3 THEN '3º Trimestre'
    WHEN 4 THEN 'Idade gestacional ignorada'
    WHEN 5 THEN 'Não'
    WHEN 6 THEN 'Não se aplica'
    WHEN 9 THEN 'Ignorado'
    ELSE 'Não Informado' 
  END AS situacao_gestacional,


-- tratamento escolaridade

CASE CAST(CS_ESCOL_N AS STRING) 
    WHEN '0' THEN 'Analfabeto'
    WHEN '1' THEN '1ª a 4ª série incompleta do EF'
    WHEN '2' THEN '4ª série completa do EF'
    WHEN '3' THEN '5ª à 8ª série incompleta do EF'
    WHEN '4' THEN 'Ensino fundamental completo'
    WHEN '5' THEN 'Ensino médio incompleto'
    WHEN '6' THEN 'Ensino médio completo'
    WHEN '7' THEN 'Educação superior incompleta'
    WHEN '8' THEN 'Educação superior completa'
    WHEN '9' THEN 'Ignorado'
    WHEN '10' THEN 'Não se aplica'
    ELSE 'Não informado' 
  END AS escolaridade,

-- tratamento situação de trabalho

CASE CAST(SIT_TRAB AS STRING)
    WHEN '1' THEN 'Empregado registrado CLT'
    WHEN '2' THEN 'Empregado não registrado'
    WHEN '3' THEN 'Autônomo'
    WHEN '4' THEN 'Servidor público estatutário'
    WHEN '5' THEN 'Servidor público celetista'
    WHEN '6' THEN 'Aposentado'
    WHEN '7' THEN 'Desempregado'
    WHEN '8' THEN 'Trabalho temporário'
    WHEN '9' THEN 'Cooperativado'
    WHEN '10' THEN 'Trabalhador avulso'
    WHEN '11' THEN 'Empregador'
    WHEN '12' THEN 'Outros'
    WHEN '99' THEN 'Ignorado'
    ELSE 'Não informado'
  END AS situacao_trabalho,

-- tratamento atendimento médico

  CASE CAST(ATENDE_MED AS STRING)
    WHEN '1' THEN 'Sim'
    WHEN '2' THEN 'Não'
    WHEN '9' THEN 'Ignorado'
    ELSE 'Não informado'
  END AS recebeu_atendimento_medico,

-- tratamento da evolução do caso

  CASE CAST(EVOLUCAO AS STRING)
    WHEN '1' THEN 'Cura'
    WHEN '2' THEN 'Incapacidade temporária'
    WHEN '3' THEN 'Incapacidade permanente'
    WHEN '4' THEN 'Incapacidade total permanente'
    WHEN '5' THEN 'Óbito por acidente de trabalho'
    WHEN '6' THEN 'Óbito por outras causas'
    WHEN '7' THEN 'Outro'
    WHEN '9' THEN 'Ignorado'
    ELSE 'Não informado'
  END AS evolucao_caso,

-- tratamento do regime de tratamento
  CASE CAST(REGIME AS STRING)
    WHEN '1' THEN 'Hospitalar'
    WHEN '2' THEN 'Ambulatorial'
    WHEN '3' THEN 'Outro'
    WHEN '9' THEN 'Ignorado'
    ELSE 'Não informado'
  END AS regime_tratamento,

-- referencial da tabela
FROM
  ${ref("acidentes_de_trabalho_silver")}