config {
    type:"view",
    schema:"dados_alagoinhas_gold",
    name:"tuberculose_alagoinhas_historico_v",
    description:"Tratamento de dados históricos sobre tuberculose em Alagoinhas"
}

-- Base inicialmente tratada no BigQuery, fizemos o ajuste com REPLACE para tratar apenas novas colunas específicas em seus valores

SELECT * 
  REPLACE(
    --- tratamento de sexo
    CASE
      WHEN CS_SEXO = "F" THEN "Feminino"
      WHEN CS_SEXO = "M" THEN "Masculino"
      ELSE "Ignorado"
    END AS CS_SEXO

    --- tratamento de escolaridade
  )   

FROM

${ref("tuberculose_alagoinhas_historico_silver")}

