config {
    type: "view",
    schema: "dados_alagoinhas_gold",
    name:"animaispeconhentos_2026_alagoinhas_gold_v",
    description: "Base tratada de dados sobre acidentes com animais peçomhentos em Alagoinhas durante a série histporica",

// Documentação das colunas para o Knowledge Catalog
columns: {
    data_notificacao: "Descreve a data de notificação na unidade de saúde",
    ano: "Descreve o ano de notificação",
    data_primeiros_sintomas: "Descreve a data dos primeiros sintomas",
    idade_em_anos: "Descreve a idade em anos do paciente",
    sexo: "Descreve o sexo do paciente",
    raca: "Descreve a raca/cor do paciente"}
}

SELECT 
  DT_NOTIFIC AS data_notificacao,
  NU_ANO AS ano,
  DT_SIN_PRI AS data_primeiros_sintomas,


-- tratamento idade do paciente
CASE 
    WHEN NU_IDADE_N >= 4000 AND NU_IDADE_N < 5000 THEN NU_IDADE_N - 4000
    WHEN NU_IDADE_N < 4000 THEN 0
    ELSE NULL 
  END AS idade_em_anos,


-- tratamento sexo
CASE  
    WHEN CS_SEXO = 'F' THEN 'Feminino'
    WHEN CS_SEXO = 'M' THEN 'Masculino'
    ELSE 'Ignorado'
  END AS sexo,

-- tratamento raça
 CASE 
    WHEN CS_RACA = 1 THEN 'Branca'
    WHEN CS_RACA = 2 THEN 'Preta'
    WHEN CS_RACA = 3 THEN 'Amarela'
    WHEN CS_RACA = 4 THEN 'Parda'
    WHEN CS_RACA = 9 THEN 'Ignorado'
    ELSE 'Não preenchido'
  END AS raca,

--

FROM 
   ${ref("animaispeconhentos_alagoinhas_2026_silver")}

