config {

    type: "view",
    schema: "dados_alagoinhas_gold",
    name:"animaispeconhentos_2026_alagoinhas_gold_v",
    description: "Base tratada de dados sobre acidentes com animais peçomhentos em Alagoinhas durante a série histporica",

labels: {
    autor: "luciano",
    departamento: "saude",
  },

columns: {
    data_notificacao: "Descreve a data de notificação na unidade de saúde",
    ano: "Descreve o ano de notificação",
    data_primeiros_sintomas: "Descreve a data dos primeiros sintomas",
    idade_em_anos: "Descreve a idade em anos do paciente",
    sexo: "Descreve o sexo do paciente",
    raca: "Descreve a raca/cor do paciente"}

}




SELECT 
  DT_NOTIFIC AS data_notificacao,
  NU_ANO AS ano,
  DT_SIN_PRI AS data_primeiros_sintomas,


-- tratamento idade do paciente
CASE 
    WHEN NU_IDADE_N >= 4000 AND NU_IDADE_N < 5000 THEN NU_IDADE_N - 4000
    WHEN NU_IDADE_N < 4000 THEN 0
    ELSE NULL 
  END AS idade_em_anos,


-- tratamento sexo
CASE  
    WHEN CS_SEXO = 'F' THEN 'Feminino'
    WHEN CS_SEXO = 'M' THEN 'Masculino'
    ELSE 'Ignorado'
  END AS sexo,

-- tratamento raça
 CASE 
    WHEN CS_RACA = 1 THEN 'Branca'
    WHEN CS_RACA = 2 THEN 'Preta'
    WHEN CS_RACA = 3 THEN 'Amarela'
    WHEN CS_RACA = 4 THEN 'Parda'
    WHEN CS_RACA = 9 THEN 'Ignorado'
    ELSE 'Não preenchido'
  END AS raca,

-- tratamento situação gestacional

-- tratamento escolaridade

-- tratamento local da lesao

CASE
    WHEN ANT_LOCA_1 = 1 THEN 'Cabeça'
    WHEN ANT_LOCA_1 = 2 THEN 'Braço'
    WHEN ANT_LOCA_1 = 3 THEN 'Antebraço'
    WHEN ANT_LOCA_1 = 4 THEN 'Mão'
    WHEN ANT_LOCA_1 = 5 THEN 'Dedo da mão'
    WHEN ANT_LOCA_1 = 6 THEN 'Tronco'
    WHEN ANT_LOCA_1 = 7 THEN 'Coxa'
    WHEN ANT_LOCA_1 = 8 THEN 'Perna'
    WHEN ANT_LOCA_1 = 9 THEN 'Pé'
    WHEN ANT_LOCA_1 = 10 THEN 'Dedo do pé'
    WHEN ANT_LOCA_1 = 99 THEN 'Ignorado'
    ELSE 'Não informado'
END AS local_picada_1,

-- tratamento tipo de acidente

CASE
    WHEN TP_ACIDENT = 1 THEN 'Serpente'
    WHEN TP_ACIDENT = 2 THEN 'Aranha'
    WHEN TP_ACIDENT = 3 THEN 'Escorpião'
    WHEN TP_ACIDENT = 4 THEN 'Lagarta'
    WHEN TP_ACIDENT = 5 THEN 'Abelha'
    WHEN TP_ACIDENT = 6 THEN 'Outros'
    WHEN TP_ACIDENT = 9 THEN 'Ignorado'
    ELSE 'Não informado'
END AS tipo_acidente,

FROM 
   ${ref("animaispeconhentos_alagoinhas_2026_silver")}

