config {
    type:"table",
    schema:"dados_alagoinhas_gold",
    name:"violencia_alagoinhas_gold_v",
    description: "Tratamento de dados sobre violência interpessoal ou autoprovocada",

labels: {
  autor:"luciano",
  departamento:"saude"
},

columns: {
   data_notificacao: "Descreve a data de notificação da ocorrência",
   ano_v: "Descreve o ano da ocorrência",
   sexo: "Descreve o sexo do paciente com o agravo",
   situacao_gestacional:"Descreve a situação gestacional do paciente (para o sexo feminino)",
   raca_cor:"Descreve a raça/cor do paciente"
}}

SELECT 
    DT_NOTIFIC AS data_notificacao,
    NU_ANO AS ano_v,

 -- transformação sexo   
CASE 
    WHEN CS_SEXO = "F" THEN "Feminino"
    WHEN CS_SEXO = "M" THEN "Masculino"
    WHEN CS_SEXO = "I" THEN "Ignorado"
    WHEN CS_SEXO IS NULL THEN "Não especificado"
END AS sexo,

-- transformação situação gestacional
CASE
    WHEN CS_GESTANT = 1 THEN '1º trimestre'
    WHEN CS_GESTANT = 2 THEN '2º trimestre'
    WHEN CS_GESTANT = 3 THEN '3º trimestre'
    WHEN CS_GESTANT = 4 THEN 'Idade gestacional ignorada'
    WHEN CS_GESTANT = 5 THEN 'Não'
    WHEN CS_GESTANT = 6 THEN 'Não se aplica'
    WHEN CS_GESTANT = 9 THEN 'Ignorado'
    ELSE 'Não preenchido'
  END AS situacao_gestacional,

-- transformação raça cor
CASE
    WHEN CS_RACA = 1 THEN 'Branca'
    WHEN CS_RACA = 2 THEN 'Preta'
    WHEN CS_RACA = 3 THEN 'Amarela'
    WHEN CS_RACA = 4 THEN 'Parda'
    WHEN CS_RACA = 5 THEN 'Indígena'
    WHEN CS_RACA = 9 THEN 'Ignorado'
    ELSE 'Não preenchido' 
  END AS raca_cor,

-- transformação escolaridade
CASE
    WHEN CS_ESCOL_N = 0 THEN 'Analfabeto'
    WHEN CS_ESCOL_N = 1 THEN '1ª a 4ª série incompleta do EF'
    WHEN CS_ESCOL_N = 2 THEN '4ª série completa do EF'
    WHEN CS_ESCOL_N = 3 THEN '5ª à 8ª série incompleta do EF'
    WHEN CS_ESCOL_N = 4 THEN 'Ensino fundamental completo'
    WHEN CS_ESCOL_N = 5 THEN 'Ensino médio incompleto'
    WHEN CS_ESCOL_N = 6 THEN 'Ensino médio completo'
    WHEN CS_ESCOL_N = 7 THEN 'Educação superior incompleta'
    WHEN CS_ESCOL_N = 8 THEN 'Educação superior completa'
    WHEN CS_ESCOL_N = 9 THEN 'Ignorado'
    WHEN CS_ESCOL_N = 10 THEN 'Não se aplica'
    WHEN CS_ESCOL_N IS NULL THEN 'Não preenchido'
    ELSE 'Outro/Não informado' 
  END AS escolaridade,

-- transformação situação conjugal
  CASE
    WHEN SIT_CONJUG = 1 THEN 'Solteiro(a)'
    WHEN SIT_CONJUG = 2 THEN 'Casado(a)/União consensual'
    WHEN SIT_CONJUG = 3 THEN 'Viúvo(a)'
    WHEN SIT_CONJUG = 4 THEN 'Divorciado(a)'
    WHEN SIT_CONJUG = 8 THEN 'Não se aplica'
    WHEN SIT_CONJUG = 9 THEN 'Ignorado'
    WHEN SIT_CONJUG IS NULL THEN 'Não preenchido'
    ELSE 'Outro/Fora do padrão' 
  END AS situacao_conjugal,

-- transformação local de ocorrência

CASE
    WHEN CAST(LOCAL_OCOR AS STRING) = '1' THEN 'Hospital'
    WHEN CAST(LOCAL_OCOR AS STRING) = '2' THEN 'Outro estabelecimento de saúde'
    WHEN CAST(LOCAL_OCOR AS STRING) = '3' THEN 'Domicílio'
    WHEN CAST(LOCAL_OCOR AS STRING) = '4' THEN 'Via pública'
    WHEN CAST(LOCAL_OCOR AS STRING) = '5' THEN 'Outros'
    WHEN CAST(LOCAL_OCOR AS STRING) = '6' THEN 'Aldeia Indígena'
    WHEN CAST(LOCAL_OCOR AS STRING) = '7' THEN 'Comércio/Serviços'
    WHEN CAST(LOCAL_OCOR AS STRING) = '8' THEN 'Indústria/Construção'
    WHEN CAST(LOCAL_OCOR AS STRING) = '9' THEN 'Ignorado'
    WHEN CAST(LOCAL_OCOR AS STRING) = '99' THEN 'Ignorado' 
    ELSE 'Não Informado' 
  END AS local_ocorrencia_desc,

-- transformação de recorrência

CASE
    WHEN CAST(OUT_VEZES AS STRING) = '1' THEN 'Sim'
    WHEN CAST(OUT_VEZES AS STRING) = '2' THEN 'Não'
    WHEN CAST(OUT_VEZES AS STRING) = '9' THEN 'Ignorado'
    ELSE 'Não Informado' -- Trata os casos nulos (em branco na ficha)
  END AS ocorreu_outras_vezes,

-- transforamção lesão autoprovocada

CASE
    WHEN CAST(LES_AUTOP AS STRING) = '1' THEN 'Sim'
    WHEN CAST(LES_AUTOP AS STRING) = '2' THEN 'Não'
    WHEN CAST(LES_AUTOP AS STRING) = '9' THEN 'Ignorado'
    ELSE 'Não Informado'
  END AS lesao_autoprovocada,


-- transformação motivo da violência

CASE
    WHEN CAST(VIOL_MOTIV AS STRING) = '1' THEN 'Sexismo'
    WHEN CAST(VIOL_MOTIV AS STRING) = '2' THEN 'Homofobia/Lesbofobia/Bifobia/Transfobia'
    WHEN CAST(VIOL_MOTIV AS STRING) = '3' THEN 'Racismo'
    WHEN CAST(VIOL_MOTIV AS STRING) = '4' THEN 'Intolerância Religiosa'
    WHEN CAST(VIOL_MOTIV AS STRING) = '5' THEN 'Xenofobia'
    WHEN CAST(VIOL_MOTIV AS STRING) = '6' THEN 'Conflito Geracional'
    WHEN CAST(VIOL_MOTIV AS STRING) = '7' THEN 'Situação de Rua'
    WHEN CAST(VIOL_MOTIV AS STRING) = '8' THEN 'Deficiência'
    WHEN CAST(VIOL_MOTIV AS STRING) = '9' THEN 'Outros'
    WHEN CAST(VIOL_MOTIV AS STRING) = '88' THEN 'Não se aplica'
    WHEN CAST(VIOL_MOTIV AS STRING) = '99' THEN 'Ignorado'
    ELSE 'Não Informado'
  END AS motivo_violencia,

-- transformação orientação sexual

CASE
    WHEN CAST(ORIENT_SEX AS STRING) = '1' THEN 'Heterossexual'
    WHEN CAST(ORIENT_SEX AS STRING) = '2' THEN 'Homossexual (Gay/Lésbica)'
    WHEN CAST(ORIENT_SEX AS STRING) = '3' THEN 'Bissexual'
    WHEN CAST(ORIENT_SEX AS STRING) = '8' THEN 'Não se aplica'
    WHEN CAST(ORIENT_SEX AS STRING) = '9' THEN 'Ignorado'
    ELSE 'Não Informado'
  END AS orientacao_sexual,

-- transformação idade anos

CASE 
    -- Idade em anos (começa com 4): extrai os últimos 3 dígitos
    WHEN SUBSTR(CAST(NU_IDADE_N AS STRING), 1, 1) = '4' THEN CAST(SUBSTR(CAST(NU_IDADE_N AS STRING), 2, 3) AS INT64)
    -- Idade > 100 anos (começa com 5): extrai os 3 dígitos e soma 100 (Ex: 5002 = 102 anos)
    WHEN SUBSTR(CAST(NU_IDADE_N AS STRING), 1, 1) = '5' THEN 100 + CAST(SUBSTR(CAST(NU_IDADE_N AS STRING), 2, 3) AS INT64)
    -- Bebês (1=Horas, 2=Dias, 3=Meses): idade em anos completos é 0
    WHEN SUBSTR(CAST(NU_IDADE_N AS STRING), 1, 1) IN ('1', '2', '3') THEN 0
    -- Ignorados ou não preenchidos viram NULL
    ELSE NULL 
  END AS idade,

-- transformação identidade de gênero

CASE 
    WHEN CAST(IDENT_GEN AS STRING) = '1' THEN 'Travesti'
    WHEN CAST(IDENT_GEN AS STRING) = '2' THEN 'Mulher Transexual'
    WHEN CAST(IDENT_GEN AS STRING) = '3' THEN 'Homem Transexual'
    WHEN CAST(IDENT_GEN AS STRING) = '8' THEN 'Não se aplica (Cisgênero/Menor)'
    WHEN CAST(IDENT_GEN AS STRING) = '9' THEN 'Ignorado'
    ELSE 'Não Preenchido/Nulo'
  END AS identidade_genero,

  -- transformação local de ocorrÊncia

CASE 
    WHEN CAST(LOCAL_OCOR AS STRING) IN ('1', '01') THEN 'Residência'
    WHEN CAST(LOCAL_OCOR AS STRING) IN ('2', '02') THEN 'Habitação Coletiva'
    WHEN CAST(LOCAL_OCOR AS STRING) IN ('3', '03') THEN 'Escola'
    WHEN CAST(LOCAL_OCOR AS STRING) IN ('4', '04') THEN 'Local de Prática Esportiva'
    WHEN CAST(LOCAL_OCOR AS STRING) IN ('5', '05') THEN 'Bar ou Similar'
    WHEN CAST(LOCAL_OCOR AS STRING) IN ('6', '06') THEN 'Via Pública'
    WHEN CAST(LOCAL_OCOR AS STRING) IN ('7', '07') THEN 'Comércio/Serviços'
    WHEN CAST(LOCAL_OCOR AS STRING) IN ('8', '08') THEN 'Indústria/Construção'
    WHEN CAST(LOCAL_OCOR AS STRING) IN ('9', '09') THEN 'Outro'
    WHEN CAST(LOCAL_OCOR AS STRING) = '99' THEN 'Ignorado'
    ELSE 'Não Preenchido/Nulo'
  END AS local_ocorrencia_descricao,

--- transformação agressor

CASE 
    WHEN CAST(AUTOR_SEXO AS STRING) = '1' THEN 'Masculino'
    WHEN CAST(AUTOR_SEXO AS STRING) = '2' THEN 'Feminino'
    WHEN CAST(AUTOR_SEXO AS STRING) = '3' THEN 'Ambos os sexos'
    WHEN CAST(AUTOR_SEXO AS STRING) = '9' THEN 'Ignorado'
    ELSE 'Não Preenchido/Nulo'
  END AS agressor_perfil_sexo,

-- referencial da base
FROM
 ${ref("violencia_alagoinhas_silver")}
































