config {
  type: "view",
  schema: "dados_alagoinhas_gold",
  name: "mortalidade_alagoinhas_gold",
  description: "Mantém a base de dados sobre mortalidade em Alagoinhas"
}

SELECT 
  CASE
    WHEN CAST(TIPOBITO AS STRING) = '1' THEN 'Óbito fetal'
    WHEN CAST(TIPOBITO AS STRING) = '2' THEN 'Óbito não fetal'
  END AS tipo_obito,

  PARSE_DATE('%d%m%Y', LPAD(CAST(DTOBITO AS STRING), 8, '0')) AS data_obito,

  HORAOBITO AS hora_obito,
  `NATURAL` AS naturalidade,

  CASE
    WHEN IDADE >= 400 AND IDADE < 500 THEN IDADE - 400
    WHEN IDADE >= 500 AND IDADE < 600 THEN (IDADE - 500) + 100
    WHEN IDADE > 0 AND IDADE < 400 THEN 0
    ELSE NULL
  END AS idade_anos,

  CASE
    WHEN CAST(SEXO AS STRING) = '2' THEN 'Feminino'
    WHEN CAST(SEXO AS STRING) = '1' THEN 'Masculino'
    WHEN CAST(SEXO AS STRING) = '9' THEN 'Ignorado'
  END AS sexo,

  RACACOR AS raca,

  ESTCIV AS estado_civil,
  ESC AS escolaridade
FROM ${ref("mortalidade_alagoinhas_silver")}